# Generated by Django 2.1 on 2020-01-03 09:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KM', '0002_auto_20200103_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agenda', models.CharField(choices=[('Penelitian', 'Penelitian'), ('Advokasi', 'Advokasi'), ('Peningkatan Kapasitas', 'Peningkatan Kapasitas'), ('Pelayanan Komunitas', 'Pelayanan Komunitas')], default='Penelitian', max_length=25)),
                ('judul', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('subjudul', models.CharField(blank=True, max_length=200, null=True)),
                ('isi', ckeditor.fields.RichTextField()),
                ('lokasi', models.CharField(max_length=200)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('link', models.URLField(default='#')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/web/acara/')),
                ('ket_gambar', models.CharField(blank=True, max_length=50)),
                ('download', models.FileField(blank=True, null=True, upload_to='document/web/acara/')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('dirubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kategori', models.CharField(choices=[('Artikel', 'Artikel'), ('Dokumentasi', 'Dokumentasi')], default='Dokumentasi', max_length=25)),
                ('Agenda', models.CharField(choices=[('Penelitian', 'Penelitian'), ('Advokasi', 'Advokasi'), ('Peningkatan Kapasitas', 'Peningkatan Kapasitas'), ('Pelayanan Komunitas', 'Pelayanan Komunitas')], default='Penelitian', max_length=25)),
                ('judul', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('tanggal', models.DateField()),
                ('isi', ckeditor.fields.RichTextField()),
                ('sumber', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/web/berita')),
                ('ket_gambar', models.CharField(blank=True, max_length=100, null=True)),
                ('download', models.FileField(blank=True, null=True, upload_to='document/web/berita')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('dirubah', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Staff')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
            },
        ),
        migrations.CreateModel(
            name='downloadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dokumen', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Download',
            },
        ),
        migrations.CreateModel(
            name='HomeSLide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('slide1_img', models.ImageField(upload_to='images/web/homepage')),
                ('Slide1_desc', models.CharField(max_length=30)),
                ('Slide1_link', models.TextField(default='#')),
                ('slide2_img', models.ImageField(upload_to='images/web/homepage')),
                ('Slide2_desc', models.CharField(max_length=30)),
                ('Slide2_link', models.TextField(default='#')),
                ('slide3_img', models.ImageField(upload_to='images/web/homepage')),
                ('Slide3_desc', models.CharField(max_length=30)),
                ('Slide3_link', models.TextField(default='#')),
                ('tentang_kami', models.ImageField(default=True, upload_to='images/web/homepage')),
                ('pustaka', models.ImageField(default=True, upload_to='images/web/homepage')),
                ('kesehatan', models.ImageField(default=True, upload_to='images/web/homepage')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('kesjiw_banner', ckeditor.fields.RichTextField(null=True)),
                ('kesjiw_history', ckeditor.fields.RichTextField(null=True)),
                ('kesjiw_history_highlight', ckeditor.fields.RichTextField(null=True)),
                ('pustaka_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('pustaka_HIV_judul', models.CharField(blank=True, max_length=100, null=True)),
                ('pustaka_HIV_ket', models.CharField(blank=True, max_length=250, null=True)),
                ('pustaka_publikasi_judul', models.CharField(blank=True, max_length=100, null=True)),
                ('pustaka_publikasi_ket', models.CharField(blank=True, max_length=250, null=True)),
                ('pustaka_regulasi_judul', models.CharField(blank=True, max_length=100, null=True)),
                ('pustaka_regulasi_ket', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Web Settings',
                'verbose_name_plural': 'Web Settings',
            },
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kntk', models.CharField(max_length=50, null=True)),
                ('email_kntk', models.EmailField(blank=True, max_length=254, null=True)),
                ('telp_kntk', models.CharField(blank=True, max_length=15, null=True)),
                ('org_kntk', models.CharField(blank=True, max_length=150, null=True)),
                ('pesan_kntk', models.TextField(blank=True, null=True)),
                ('tanggal_kntk', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kontak',
                'verbose_name_plural': 'Kontak',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TentangKami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('sejarah', ckeditor.fields.RichTextField()),
                ('history', ckeditor.fields.RichTextField()),
                ('visi', models.TextField()),
                ('vison', models.TextField()),
                ('misi', models.TextField()),
                ('mission', models.TextField()),
            ],
            options={
                'verbose_name': 'Tentang Kami',
                'verbose_name_plural': 'tentang Kami',
            },
        ),
    ]
