# Generated by Django 2.1.7 on 2020-02-05 22:55

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0001_initial'),
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acara',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='berita',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='downloadform',
            name='organisasi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='penulis',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='KM.Staff'),
        ),
    ]
