# Generated by Django 2.2 on 2020-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_auto_20200205_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadform',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
