# Generated by Django 2.1.7 on 2020-01-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lazysignup', '0002_auto_20150430_1100'),
        ('WEB', '0002_auto_20200103_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('institusi', models.CharField(blank=True, max_length=250)),
                ('users_lazy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lazysignup.LazyUser')),
            ],
        ),
    ]
