# Generated by Django 3.1 on 2020-09-02 12:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_downloadform_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='about_desc',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='about_desc_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='Agenda',
            field=models.CharField(choices=[('Penelitian', 'Penelitian'), ('Advokasi', 'Advokasi'), ('Peningkatan Kapasitas', 'Peningkatan Kapasitas'), ('Pelayanan Komunitas', 'Pelayanan Komunitas'), ('Newsletter', 'Newsletter')], default='Penelitian', max_length=25),
        ),
    ]
