# Generated by Django 2.2 on 2020-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadform',
            name='organisasi',
            field=models.TextField(blank=True),
        ),
    ]
