# Generated by Django 3.1 on 2020-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_auto_20200902_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='Kategori',
            field=models.CharField(choices=[('Artikel', 'Artikel'), ('Dokumentasi', 'Dokumentasi'), ('Newsletter', 'Newsletter')], default='Dokumentasi', max_length=25),
        ),
    ]
