# Generated by Django 3.1 on 2020-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_auto_20200902_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
