# Generated by Django 3.1 on 2020-09-14 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_auto_20200902_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='about_cop',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='cop',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
