# Generated by Django 3.1 on 2020-09-17 03:51

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('WEB', '0007_auto_20200914_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('ket', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Peneliti',
                'verbose_name_plural': 'Peneliti',
            },
        ),
        migrations.CreateModel(
            name='TaggedAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_taggedauthor_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_taggedauthor_items', to='WEB.author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.AddField(
            model_name='berita',
            name='penulis_luar',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='abstracts', through='WEB.TaggedAuthor', to='WEB.Author', verbose_name='Author'),
        ),
    ]
