# Generated by Django 3.1 on 2020-09-17 07:43

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0017_personalevent_owner'),
        ('WEB', '0008_auto_20200917_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='penulis',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.PROTECT, to='KM.staff'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='penulis_luar',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='abstracts', through='WEB.TaggedAuthor', to='WEB.Author', verbose_name='Penulis Lain'),
        ),
    ]
