# Generated by Django 3.1 on 2020-09-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0017_personalevent_owner'),
        ('WEB', '0009_auto_20200917_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='penulis',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KM.staff'),
        ),
    ]
