# Generated by Django 3.1 on 2020-09-22 11:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('WEB', '0010_auto_20200917_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAnotated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Annotated Tags',
                'verbose_name_plural': 'Annotated Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedAnnotated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_taggedannotated_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_taggedannotated_items', to='WEB.taganotated')),
            ],
            options={
                'verbose_name': 'Annotate Tags',
                'verbose_name_plural': 'Annotate Tags',
            },
        ),
        migrations.CreateModel(
            name='AnotatedCOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('tanggal', models.DateField()),
                ('sumber', models.CharField(blank=True, max_length=120)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('DOI_number', models.CharField(blank=True, max_length=120)),
                ('DOI_URL', models.URLField(blank=True)),
                ('doctype', models.CharField(blank=True, max_length=4)),
                ('url', models.URLField(blank=True)),
                ('download', models.FileField(blank=True, upload_to='anotated/')),
                ('bibliografi', ckeditor.fields.RichTextField(blank=True)),
                ('anotated', ckeditor.fields.RichTextField(blank=True)),
                ('visit_num', models.PositiveIntegerField(default=0)),
                ('Author', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='+', through='WEB.TaggedAuthor', to='WEB.Author', verbose_name='Author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tagannotated', through='WEB.TaggedAnnotated', to='WEB.TagAnotated', verbose_name='Annotated Tags')),
            ],
            options={
                'verbose_name': 'Anotated COP',
                'verbose_name_plural': 'Anotated COP',
            },
        ),
    ]
