# Generated by Django 3.1 on 2020-09-27 09:47

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0011_anotatedcop_taganotated_taggedannotated'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananKeswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('provinsi', models.CharField(choices=[('AC', 'Aceh'), ('SU', 'Sumatera Utara'), ('SB', 'Sumatera Barat'), ('RI', 'Riau'), ('KR', 'Kepulauan Riau'), ('JA', 'Jambi'), ('BE', 'Bengkulu'), ('SS', 'Sumatera Selatan'), ('BB', 'Kepulauan bangka Belitung'), ('LA', 'lampung'), ('BT', 'Banten'), ('JB', 'Jawa Barat'), ('JK', 'Jakarta'), ('JT', 'Jawa Tengah'), ('YO', 'Yogyakarta'), ('JI', 'Jawa Timur'), ('BA', 'Bali'), ('NB', 'Nusa Tenggara Barat'), ('NT', 'Nusa Tenggara Timur'), ('KB', 'Kalimantan Barat'), ('KS', 'Kalimantan Selatan'), ('KT', 'Kalimantan Tengah'), ('KI', 'Kalimantan Timur'), ('KU', 'kalimantan Utara'), ('GO', 'Gorontalo'), ('SR', 'Sulawesi Barat'), ('SN', 'Sulawesi Selatan'), ('ST', 'Sulawesi Tengah'), ('SG', 'Sulawesi Tenggara'), ('SA', 'Sulawesi Utara'), ('MA', 'Maluku'), ('MU', 'Maluku Utara'), ('PB', 'Papua Barat'), ('PA', 'Papua')], max_length=3)),
                ('kota', models.CharField(max_length=50)),
                ('kategori', models.CharField(choices=[('1', 'RSUD/RSJ'), ('2', 'Puskesmas'), ('3', 'Klinik/Layanan Swasta')], max_length=3)),
                ('deskripsi', ckeditor.fields.RichTextField()),
                ('nomor_hp', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Nomor Hp menggunakan format: '+999999999'. maksimal nomor hp yaitu 15 karakter.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'layanan Kesehatan Jiwa',
                'verbose_name_plural': 'layanan Kesehatan Jiwa',
            },
        ),
    ]
