# Generated by Django 3.1 on 2020-09-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0012_layanankeswa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layanankeswa',
            old_name='nomor_hp',
            new_name='telpon',
        ),
    ]
