# Generated by Django 3.1 on 2020-09-27 11:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0013_auto_20200927_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanankeswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='layanankeswa',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
