# Generated by Django 3.1 on 2020-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0014_auto_20200927_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanankeswa',
            name='kategori',
            field=models.CharField(choices=[('RSUD/RSJ', 'RSUD/RSJ'), ('Puskesmas', 'Puskesmas'), ('Klinik/Layanan Swasta', 'Klinik/Layanan Swasta')], max_length=25),
        ),
        migrations.AlterField(
            model_name='layanankeswa',
            name='provinsi',
            field=models.CharField(choices=[('Aceh', 'Aceh'), ('Sumatera Utara', 'Sumatera Utara'), ('Sumatera Barat', 'Sumatera Barat'), ('Riau', 'Riau'), ('Kepulauan Riau', 'Kepulauan Riau'), ('Jambi', 'Jambi'), ('Bengkulu', 'Bengkulu'), ('Sumatera Selatan', 'Sumatera Selatan'), ('Kepulauan bangka Belitung', 'Kepulauan bangka Belitung'), ('lampung', 'lampung'), ('Banten', 'Banten'), ('Jawa Barat', 'Jawa Barat'), ('Jakarta', 'Jakarta'), ('Jawa Tengah', 'Jawa Tengah'), ('Yogyakarta', 'Yogyakarta'), ('Jawa Timur', 'Jawa Timur'), ('Bali', 'Bali'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Timur', 'Kalimantan Timur'), ('kalimantan Utara', 'kalimantan Utara'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Maluku', 'Maluku'), ('Maluku Utara', 'Maluku Utara'), ('Papua Barat', 'Papua Barat'), ('Papua', 'Papua')], max_length=30),
        ),
    ]
