# Generated by Django 3.1 on 2021-03-11 15:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0016_auto_20201030_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('sejarah', ckeditor.fields.RichTextField()),
                ('history', ckeditor.fields.RichTextField()),
                ('visi', models.TextField()),
                ('vison', models.TextField()),
                ('misi', models.TextField()),
                ('mission', models.TextField()),
            ],
            options={
                'verbose_name': 'Tentang Kami',
                'verbose_name_plural': 'tentang Kami',
            },
        ),
    ]
