# Generated by Django 3.1 on 2021-06-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0017_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='Kategori',
            field=models.CharField(choices=[('Artikel', 'Artikel'), ('Dokumentasi', 'Dokumentasi')], default='Dokumentasi', max_length=25),
        ),
    ]
