# Generated by Django 2.1 on 2020-01-03 09:59

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenPenelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kategori', models.CharField(choices=[('Proposal - Penelitian', 'Proposal Penelitian'), ('Proposal - Budget Plan', 'Proposal Budget Plan'), ('Proposal - Protokol Penelitian', 'Proposal Protokol Penelitian'), ('Referensi - Nasional', 'Referensi Nasional'), ('Referensi - Interasional', 'Referensi Interasional'), ('Instrumen - Kuantitatif', 'Instrumen Kuantitatif'), ('Instrumen - Kualitatif', 'Instrumen Kualitatif'), ('Data - Kuantitatif', 'Data Kuantitatif'), ('Data - Kualitatif', 'Data Kualitatif'), ('Hasil Analisis - Kuantitatif', 'Hasil Analisis Kuantitatif'), ('Hasil Analisis - Kualitatif', 'Hasil Analisis Kualitatif'), ('Laporan Penelitian', 'Laporan Penelitian'), ('Diseminasi Penelitian - Kerangka Acuan', 'Diseminasi Penelitian Kerangka Acuan'), ('Diseminasi Penelitian - Materi', 'Diseminasi Penelitian Materi'), ('Diseminasi Penelitian - Notulensi', 'Diseminasi Penelitian Notulensi'), ('Diseminasi Penelitian - Foto', 'Diseminasi Penelitian Foto'), ('Diseminasi Penelitian - Daftar Hadir', 'Diseminasi Penelitian Daftar Hadir'), ('Administrasi dan Keuangan - Izin Penelitian', 'Administrasi dan Keuangan Izin Penelitian'), ('Administrasi dan Keuangan - Ethical Clearance', 'Administrasi dan Keuangan Ethical Clearance'), ('Administrasi dan Keuangan - Kontrak atau MoU', 'Administrasi dan Keuangan Kontrak atau MoU'), ('Administrasi dan Keuangan - Laporan Keuangan', 'Administrasi dan Keuangan Laporan Keuangan'), ('Pertemuan dan rapat - Notulensi', 'Pertemuan dan rapat - Notulensi')], max_length=60)),
                ('Judul', models.TextField(blank=True)),
                ('dokumen', models.FileField(upload_to='KM/dokumenpenelitian')),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Dokumen Penelitian',
                'verbose_name_plural': 'Dokumen Penelitian',
            },
        ),
        migrations.CreateModel(
            name='DokumenPeningkatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Substansi - Kerangka Acuan', 'Substansi - Kerangka Acuan'), ('Substansi - Budget Plan', 'SUbstansi - Budget Plan'), ('Pendukung - Poster', 'Pendukung - Poster'), ('Pendukung - Foto', 'Pendukung - Foto'), ('Pendukung - Daftar Hadir', 'Pendukung - Daftar Hadir'), ('Pendukung - Evaluasi Peserta', 'Pendukung - Evaluasi Peserta'), ('Pendukung - Laporan Keuangan', 'Pendukung - Laporan Keuangan')], max_length=35)),
                ('dokumen', models.FileField(upload_to='KM/peningkatankapasitas')),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Dokumen Peningkatan',
                'verbose_name_plural': 'Dokumen Peningkatan',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('ket', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donor',
            },
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], default='Hardware', max_length=8)),
                ('jenis_barang', models.CharField(choices=[('Tab', 'Tab'), ('Recorder', 'Recorder'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Lainnya', 'Lainnya')], max_length=10)),
                ('nama_barang', models.CharField(default=True, max_length=100)),
                ('tahun_pembelian', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(upload_to='document/KM/Inventaris')),
                ('Tersedia', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Kontak_PPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_kontak', models.CharField(choices=[('Pemerintah Implementer', 'Pemerintah Implementer'), ('Pemerintah Stakeholder', 'Pemerintah Stakeholder'), ('Non Pemerintah Implementer', 'Non Pemerintah Implementer'), ('Non Pemerintah Stakeholder', 'Non Pemerintah Stakeholder')], max_length=30)),
                ('nama_organisasi', models.CharField(max_length=100)),
                ('Kontak', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=13, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True)),
                ('gambar', models.ImageField(upload_to='document/KM/Kontak')),
            ],
            options={
                'verbose_name': 'Kontak',
                'verbose_name_plural': 'Kontak',
            },
        ),
        migrations.CreateModel(
            name='Manajemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('kategori', models.CharField(choices=[('Kontrak/MOU', 'Kontrak/MOU'), ('SOP', 'SOP'), ('Template', 'Template')], max_length=20)),
                ('tahun', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='km/manajemen/')),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Manajemen',
                'verbose_name_plural': 'Manajemen',
            },
        ),
        migrations.CreateModel(
            name='MediaAdvokasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('kategori', models.CharField(choices=[('Research Report', 'Research Report'), ('Policy Brief', 'Policy Brief'), ('Lembar Fakta', 'Lembar Fakta'), ('Press release', 'Press release'), ('Infografis', 'Infografis'), ('HIV AIDS', 'HIV AIDS'), ('NAPZA', 'NAPZA'), ('Kesehatan Jiwa', 'Kesehatan Jiwa'), ('Newsletter', 'Newsletter'), ('Annual Report', 'Annual Report'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('sumber', models.CharField(blank=True, max_length=25, null=True)),
                ('tahun', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='km/mediaadvokasi/')),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Media Advokasi',
                'verbose_name_plural': 'Media Advokasi',
            },
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('kategori', models.CharField(choices=[('Kebijakan', 'Kebijakan'), ('Sosial Perilaku', 'Sosial Perilaku'), ('Bio-medis', 'Bio-medis'), ('Operasional', 'Operasional')], max_length=20)),
                ('mulai', models.DateField()),
                ('selesai', models.DateTimeField()),
                ('organisasi_mitra', models.TextField(blank=True)),
                ('mata_uang', models.CharField(max_length=10)),
                ('nominal', models.IntegerField()),
                ('status', models.CharField(choices=[('Initiating', 'Initiating'), ('Planning', 'Planning'), ('Executing', 'Executing'), ('Closing', 'Closing'), ('Completed', 'Completed')], max_length=10)),
            ],
            options={
                'verbose_name': 'Penelitian',
                'verbose_name_plural': 'Penelitian',
            },
        ),
        migrations.CreateModel(
            name='PeningkatanKapasitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('PPH UNIKA Atma Jaya', 'PPH UNIKA Atma Jaya'), ('Non PPH', 'Non PPH')], default='PPH UNIKA Atma Jaya', max_length=20)),
                ('kategori', models.CharField(choices=[('Lecture Series', 'Lecture Series'), ('Workshop dan Pelatihan', 'Workshop dan Pelatihan'), ('Pertemuan dan Seminar', 'Pertemuan dan Seminar'), ('Kursus Online', 'Kursus Online'), ('Fun Sharing Day', 'Fun Sharing Day'), ('Liputan Media', 'Liputan Media'), ('Konferensi Nasional', 'Konferensi Nasional'), ('Konferensi Internasional', 'Konferensi Internasional')], max_length=25)),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('mata_uang', models.CharField(max_length=10, null=True)),
                ('budget', models.IntegerField(null=True)),
                ('pengeluaran', models.IntegerField(null=True)),
                ('lokasi', models.TextField(blank=True, null=True)),
                ('kota', models.CharField(blank=True, max_length=15, null=True)),
                ('negara', models.CharField(blank=True, max_length=15, null=True)),
                ('penyelenggara', models.CharField(default=True, max_length=100)),
                ('peran', models.CharField(choices=[('Peserta', 'Peserta'), ('Pembicara', 'Pembicara'), ('Moderator', 'Moderator'), ('Konsultan', 'Konsultan'), ('MC', 'MC'), ('Presenter', 'Presenter')], max_length=10, null=True)),
                ('laporan_kegiatan', models.FileField(blank=True, null=True, upload_to='KM/peningkatan/laporan/')),
                ('materi', models.FileField(upload_to='KM/peningkatan/materi/')),
            ],
            options={
                'verbose_name': 'Peningkatan Kapasitas',
                'verbose_name_plural': 'Peningkatan Kapasitas',
            },
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, choices=[('HIV AIDS', 'HIV AIDS'), ('Publikasi', 'Publikasi'), ('Regulasi', 'Regulasi'), ('Lain-lain', 'Lain-lain')], default='HIV AIDS', max_length=15, null=True)),
                ('judul', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('kategori', models.CharField(choices=[('Research Report', 'Research Report'), ('Policy Brief', 'Policy Brief'), ('Lembar Fakta', 'Lembar Fakta'), ('Press release', 'Press release'), ('Infografis', 'Infografis'), ('HIV AIDS', 'HIV AIDS'), ('NAPZA', 'NAPZA'), ('Kesehatan Jiwa', 'Kesehatan Jiwa'), ('Newsletter', 'Newsletter'), ('Annual Report', 'Annual Report'), ('Lainnya', 'Lainnya')], max_length=30)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/KM/publikasi/')),
                ('deskripsi', ckeditor.fields.RichTextField()),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('download', models.FileField(upload_to='document/KM/publikasi')),
                ('web_content', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pustaka',
                'verbose_name_plural': 'Pustaka',
            },
        ),
        migrations.CreateModel(
            name='Publikasi_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.DateField()),
                ('judul', models.TextField()),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('kategori', models.CharField(choices=[('Artikel Ilmiah', 'Artikel Ilmiah'), ('Artikel Non-ilmiah', 'Artikel Non-ilmiah'), ('Policy Brief', 'Policy Brief'), ('Buku/Chapter Buku', 'Buku/Chapter Buku'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('peran', models.CharField(choices=[('Penulis Utama', 'Penulis Utama'), ('Penulis Pendamping', 'Penulis Pendamping'), ('Editor', 'Editor'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('tingkat', models.CharField(choices=[('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publikasi Staff',
                'verbose_name_plural': 'Publikasi Staff',
            },
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('SMA', 'SMA'), ('Diploma 1', 'D1'), ('Diploma 2', 'D2'), ('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], max_length=15)),
                ('nama_sekolah', models.CharField(max_length=50)),
                ('jurusan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('NIK', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('tanggal_bergabung', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, choices=[('SMA', 'SMA'), ('Diploma 1', 'D1'), ('Diploma 2', 'D2'), ('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='Strata 1', max_length=10, null=True)),
                ('hp', models.CharField(blank=True, max_length=13, null=True)),
                ('posisi', models.CharField(blank=True, default=True, max_length=150, null=True)),
                ('golongan_peneliti', models.CharField(blank=True, max_length=20, null=True)),
                ('jabatan_struktural', models.CharField(blank=True, max_length=20, null=True)),
                ('kepakaran', models.CharField(blank=True, max_length=80, null=True)),
                ('peminatan', models.CharField(blank=True, max_length=80, null=True)),
                ('Tempat_Lahir', models.CharField(blank=True, max_length=50)),
                ('Tanggal_Lahir', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/web/staff/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='km/staff/cv/')),
                ('deskripsi_singkat', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('Institusi_pendidikan', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Sekolah')),
            ],
            options={
                'verbose_name': 'Staff/Organisansi',
                'verbose_name_plural': 'Staff/Organisansi',
            },
        ),
    ]
