# Generated by Django 2.1 on 2020-01-03 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KM', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publikasi_staff',
            name='penulis',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Staff'),
        ),
        migrations.AddField(
            model_name='publikasi',
            name='penulis',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Staff'),
        ),
        migrations.AddField(
            model_name='publikasi',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Donor'),
        ),
    ]
