# Generated by Django 2.1 on 2020-01-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0003_auto_20200103_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Institusi_pendidikan',
            field=models.OneToOneField(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Sekolah'),
        ),
    ]
