# Generated by Django 2.1 on 2020-01-17 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0003_auto_20200103_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sekolah',
            options={'verbose_name': 'Pendidikan', 'verbose_name_plural': 'Pendidikan'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Institusi_pendidikan',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pendidikan_terakhir',
        ),
        migrations.AddField(
            model_name='staff',
            name='jurusan_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='jurusan_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='jurusan_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pendidikan_1',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='D3', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='pendidikan_2',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='D3', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='pendidikan_3',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='D3', max_length=10),
        ),
        migrations.AlterField(
            model_name='dokumenpenelitian',
            name='penelitian',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.Penelitian'),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='judul',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='jenjang',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Diploma 1', 'D1'), ('Diploma 2', 'D2'), ('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='Strata 1', max_length=15),
        ),
    ]
