# Generated by Django 2.1 on 2020-01-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0004_auto_20200107_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Institusi_pendidikan',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pendidikan_terakhir',
        ),
        migrations.AddField(
            model_name='staff',
            name='strata_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s1', to='KM.Sekolah'),
        ),
        migrations.AddField(
            model_name='staff',
            name='strata_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s2', to='KM.Sekolah'),
        ),
        migrations.AddField(
            model_name='staff',
            name='strata_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3', to='KM.Sekolah'),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='judul',
            field=models.CharField(max_length=150),
        ),
    ]
