# Generated by Django 2.1 on 2020-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0004_auto_20200117_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='jurusan_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pendidikan_4',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='S3', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pendidikan_2',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='S1', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pendidikan_3',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='S2', max_length=10),
        ),
    ]
