# Generated by Django 2.1 on 2020-01-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0005_auto_20200110_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sekolah',
            name='jenjang',
        ),
    ]
