# Generated by Django 2.1 on 2020-01-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0005_auto_20200117_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pendidikan_1',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pendidikan_2',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pendidikan_3',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pendidikan_4',
            field=models.CharField(blank=True, choices=[('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], max_length=10, null=True),
        ),
    ]
