# Generated by Django 2.1 on 2020-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0006_remove_sekolah_jenjang'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='jenjang',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Diploma 1', 'D1'), ('Diploma 2', 'D2'), ('Diploma 3', 'D3'), ('Strata 1', 'S1'), ('Strata 2', 'S2'), ('Strata 3', 'S3')], default='Strata 1', max_length=15),
        ),
    ]
