# Generated by Django 2.2.5 on 2020-01-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0006_auto_20200117_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontak_pph',
            name='gambar',
        ),
    ]
