# Generated by Django 2.2 on 2020-01-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0009_auto_20200127_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name': 'Jabatan', 'verbose_name_plural': 'Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='kepakaran',
            options={'verbose_name': 'Kepakaran', 'verbose_name_plural': 'Kepakaran'},
        ),
        migrations.AlterModelOptions(
            name='peminatan',
            options={'verbose_name': 'Fokus Area', 'verbose_name_plural': 'Fokus Area'},
        ),
        migrations.AlterModelOptions(
            name='posisi',
            options={'verbose_name': 'Posisi', 'verbose_name_plural': 'Posisi'},
        ),
    ]
