# Generated by Django 2.1.7 on 2020-01-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0010_auto_20200127_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sekolah',
        ),
    ]
