# Generated by Django 2.1.7 on 2020-02-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0012_auto_20200131_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenpenelitian',
            name='penelitian',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='KM.Penelitian'),
        ),
        migrations.AlterField(
            model_name='dokumenpeningkatan',
            name='Judul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KM.PeningkatanKapasitas'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='PIC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PIC_penelitian', to='KM.Staff', verbose_name='PIC Penelitian'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='principal_investigator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='Principal_investigator', to='KM.Staff', verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='penulis',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='KM.Staff'),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KM.Donor'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='kepakaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KM.Kepakaran'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='peminatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KM.Peminatan'),
        ),
    ]
