# Generated by Django 2.1.7 on 2020-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0013_auto_20200204_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='peningkatankapasitasstaff',
            name='peran',
            field=models.CharField(choices=[('Peserta', 'Peserta'), ('Pembicara', 'Pembicara'), ('Moderator', 'Moderator'), ('Konsultan', 'Konsultan'), ('MC', 'MC'), ('Presenter', 'Presenter')], default='Peserta', max_length=25),
            preserve_default=False,
        ),
    ]
