# Generated by Django 2.1.7 on 2020-02-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0014_peningkatankapasitasstaff_peran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peningkatankapasitas',
            name='laporan_kegiatan',
        ),
        migrations.RemoveField(
            model_name='peningkatankapasitas',
            name='materi',
        ),
        migrations.RemoveField(
            model_name='peningkatankapasitas',
            name='peran',
        ),
    ]
