# Generated by Django 2.2 on 2020-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0015_auto_20200205_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acara', models.CharField(max_length=250)),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
