# Generated by Django 2.1.7 on 2020-01-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0016_remove_peningkatankapasitas_staff_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeningkatanKapasitas_staff',
            new_name='PeningkatanKapasitasstaff',
        ),
        migrations.AlterField(
            model_name='inventaris',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='document/KM/Inventaris'),
        ),
    ]
