# Generated by Django 3.1 on 2020-11-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0017_personalevent_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=75)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rak',
                'verbose_name_plural': 'Rak',
            },
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='tema',
            field=models.CharField(blank=True, choices=[('HIV AIDS', 'HIV AIDS'), ('Publikasi', 'Publikasi'), ('Regulasi', 'Regulasi'), ('Lain-lain', 'Lain-lain')], default='HIV AIDS', max_length=15, null=True, verbose_name='Rak'),
        ),
    ]
