# Generated by Django 3.1 on 2020-11-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0019_rak_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publikasi',
            name='Rak',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='KM.rak'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='tema',
            field=models.CharField(blank=True, choices=[('HIV AIDS', 'HIV AIDS'), ('Publikasi', 'Publikasi'), ('Regulasi', 'Regulasi'), ('Lain-lain', 'Lain-lain')], default='HIV AIDS', max_length=15, null=True),
        ),
    ]
