# Generated by Django 3.1 on 2020-11-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0020_auto_20201113_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publikasi',
            old_name='Rak',
            new_name='rak',
        ),
    ]
