# Generated by Django 3.1 on 2020-11-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0021_auto_20201113_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publikasi',
            name='rak',
        ),
    ]
