# Generated by Django 3.1 on 2020-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0027_auto_20201115_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenpenelitian',
            name='Judul',
            field=models.TextField(),
        ),
    ]
