# Generated by Django 3.1 on 2020-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0028_auto_20201115_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi',
            name='kategori',
            field=models.CharField(choices=[('0', 'Materi Pengetahuan HIV AIDS'), ('1', 'Laporan Penelitian'), ('2', 'Policy Brief'), ('3', 'Modul'), ('4', 'SOP'), ('5', 'Infografis'), ('6', 'Artikel Jurnal Nasional & Internasional'), ('7', 'Conference'), ('8', 'Regulasi'), ('9', 'buku'), ('10', 'Laporan Pelayanan Komunitas'), ('12', 'Lecture Series'), ('13', 'Workshop'), ('11', 'Lainnya')], max_length=2),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='tema',
            field=models.CharField(blank=True, choices=[('0', 'Informasi HIV AIDS'), ('1', 'Publikasi'), ('2', 'Regulasi'), ('3', 'Penelitian'), ('4', 'Pelayanan Komunitas'), ('5', 'Peningkatan Kapasitas')], default='HIV AIDS', max_length=1, null=True, verbose_name='Rak'),
        ),
    ]
