# Generated by Django 3.1 on 2020-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0029_auto_20201122_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi',
            name='kategori',
            field=models.CharField(choices=[('0', 'Materi Pengetahuan HIV AIDS'), ('1', 'Laporan Penelitian'), ('2', 'Policy Brief'), ('3', 'Modul'), ('4', 'SOP'), ('5', 'Infografis'), ('6', 'Artikel Jurnal Nasional & Internasional'), ('7', 'Conference'), ('8', 'Regulasi'), ('9', 'buku'), ('10', 'Laporan Pelayanan Komunitas'), ('12', 'Lecture Series'), ('13', 'Workshop'), ('14', 'HIV - Aids'), ('16', 'Kesehatan Jiwa'), ('15', 'Napza'), ('17', 'Jurnal Nasional'), ('18', 'Jurnal Internasional'), ('11', 'Lainnya')], max_length=2),
        ),
    ]
