# Generated by Django 3.1 on 2021-01-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0031_auto_20201221_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi',
            name='tema',
            field=models.CharField(blank=True, choices=[('0', 'Informasi HIV AIDS'), ('1', 'Publikasi'), ('2', 'Regulasi'), ('3', 'Penelitian'), ('4', 'Pelayanan Komunitas'), ('5', 'Peningkatan Kapasitas')], default='HIV AIDS', max_length=1, null=True, verbose_name='Rak'),
        ),
    ]
