# Generated by Django 3.1 on 2021-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0032_auto_20210124_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='deskripsi_singkat',
            field=models.TextField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
