# Generated by Django 3.1 on 2021-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0033_auto_20210215_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Fellowship', 'Fellowship')], max_length=20, null=True),
        ),
    ]
