# Generated by Django 3.1 on 2021-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0034_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(blank=True, choices=[('Staff Peneliti', 'StaffPen'), ('Staff Manajemen', 'StafMan'), ('Intern & Fellowship', 'Fellowship'), ('Lainnya', 'Lainnya')], max_length=20, null=True),
        ),
    ]
