# Generated by Django 3.1 on 2021-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0035_auto_20210311_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(blank=True, choices=[('Staff Peneliti', 'Staff Peneliti'), ('Staff Manajemen', 'Staf Manajemen'), ('Intern & Fellowship', 'Intern & Fellowship'), ('Lainnya', 'Lainnya')], max_length=20, null=True),
        ),
    ]
