# Generated by Django 3.1 on 2021-06-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0036_auto_20210311_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='PIC',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='PIC_penelitian', to='KM.staff', verbose_name='PIC Penelitian'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='selesai',
            field=models.DateField(),
        ),
    ]
