# Generated by Django 3.1 on 2021-06-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0037_auto_20210629_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='selesai',
            field=models.DateTimeField(),
        ),
    ]
