# Generated by Django 2.1.7 on 2020-01-31 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0011_delete_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id_username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
