# Generated by Django 2.1.7 on 2020-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0012_auto_20200131_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeningkatanKapasitas_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Lecture Series', 'Lecture Series'), ('Workshop dan Pelatihan', 'Workshop dan Pelatihan'), ('Pertemuan dan Seminar', 'Pertemuan dan Seminar'), ('Kursus Online', 'Kursus Online'), ('Fun Sharing Day', 'Fun Sharing Day'), ('Liputan Media', 'Liputan Media'), ('Konferensi Nasional', 'Konferensi Nasional'), ('Konferensi Internasional', 'Konferensi Internasional')], max_length=25)),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('lokasi', models.TextField(blank=True, null=True)),
                ('penyelenggara', models.TextField()),
                ('laporan_kegiatan', models.FileField(blank=True, null=True, upload_to='KM/peningkatan/laporan/')),
                ('materi', models.FileField(upload_to='KM/peningkatan/materi/')),
                ('pembicara', models.ManyToManyField(to='KM.Staff')),
            ],
            options={
                'verbose_name': 'Peningkatan Kapasitas Staff',
                'verbose_name_plural': 'Peningkatan Kapasitas Staff',
            },
        ),
    ]
