# Generated by Django 2.1.7 on 2020-01-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0015_peningkatankapasitas_staff_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peningkatankapasitas_staff',
            name='author',
        ),
    ]
