# Generated by Django 2.1.7 on 2020-01-31 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KM', '0018_auto_20200131_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id_username',
        ),
        migrations.AddField(
            model_name='peningkatankapasitasstaff',
            name='peserta',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
