# Generated by Django 2.1.7 on 2020-01-31 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0019_auto_20200131_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi_staff',
            name='penulis',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
