# Generated by Django 2.1.7 on 2020-01-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0022_auto_20200131_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peningkatankapasitasstaff',
            name='peserta',
        ),
        migrations.RemoveField(
            model_name='publikasi_staff',
            name='penulis',
        ),
    ]
