# Generated by Django 2.1.7 on 2020-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0023_auto_20200131_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='peningkatankapasitasstaff',
            name='peserta',
            field=models.CharField(default='Admin.PPH', max_length=150),
        ),
        migrations.AddField(
            model_name='publikasi_staff',
            name='peserta',
            field=models.CharField(default='Admin.PPH', max_length=150),
        ),
    ]
