# Generated by Django 2.1.7 on 2020-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0024_auto_20200131_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi_staff',
            name='judul',
            field=models.CharField(default='Admin.PPH', max_length=150),
        ),
    ]
