# Generated by Django 2.1.7 on 2020-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0027_auto_20200131_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasi_staff',
            name='peserta',
            field=models.CharField(default='Admin.PPH', max_length=150),
        ),
    ]
