# Generated by Django 2.1.7 on 2020-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KM', '0028_auto_20200131_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peningkatankapasitasstaff',
            name='judul',
            field=models.CharField(default='Admin.PPH', max_length=200),
        ),
    ]
