# Generated by Django 2.1.7 on 2020-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_customuser_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gambar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
