# Generated by Django 3.1 on 2020-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_auto_20200204_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
