# Generated by Django 3.1 on 2020-08-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0010_auto_20200809_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
