# Generated by Django 3.1 on 2020-09-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0011_auto_20200810_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
